[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[provider]
cluster = "devnet"  # Must be one of: localnet, testnet, mainnet, devnet
wallet = "/Users/bimalchalise/.config/solana/id.json"

[programs.localnet]
middleware = "H93bAJi5MMPbfSARnVimEzRccdZHkATNWBj2pdRBoMXJ"

[programs.devnet]
middleware = "H93bAJi5MMPbfSARnVimEzRccdZHkATNWBj2pdRBoMXJ"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy --program-name middleware"

[workspace]
members = [
  "programs/middleware"
]